config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chats#index"

  resources :chats, only: %i[index create show] do
    resources :messages, only: %i[create]
  end

  require 'sidekiq/web'
  Sidekiq::Web.use ActionDispatch::Cookies
  Sidekiq::Web.use ActionDispatch::Session::CookieStore, key: "_interslice_session"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  enum role: {
    user: 0,
    assistant: 1
  }
  belongs_to :chat

  enum status: {
    pending: 0,
    completed: 1,
    failed: 2
  }

  broadcasts_to ->(message) { [ message.chat, "messages" ] }#, inserts_by: :append
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def create
    @chat = Chat.create
    redirect_to @chat
  end

  def show
    @chat = Chat.find params[:id]
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chat = Chat.find params[:chat_id]
    @message = @chat.messages.create message_params
    ProcessMessageJob.perform_later(@message)
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<div class="d-flex align-items-center my-3">
  <div class="flex-grow-1 fs-4">
    Chat
  </div>
  <%= form_with model: Chat.new do |form| %>
    <button class="btn btn-primary" type="submit">
      New
    </button>
  <% end %>
</div>

<ul class="list-group">
  <% Chat.all.order(id: :desc).each do |chat| %>
    <li class="list-group-item"><a href="<%= chat_path(chat) %>" >#<%= chat.id %>
    </a></li>
  <% end %>
</ul>

app/views/chats/show.html.erb
<div class="container">

    <div class="row">
        <%= turbo_frame_tag "messages" do %>
          <%= render @chat.messages %>
        <% end %>
    </div>

    <div class="row">
      <%= render partial: "messages/form", locals: { chat: @chat } %>
    </div>

    <%= turbo_stream_from @chat, :messages %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Brand</a>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GptZuo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= turbo_frame_tag "#{dom_id(chat)}_message_form" do %>
  <%= form_with(model: Message.new, url: [chat, chat.messages.new]) do |form| %>
    <div class="my-5">
      <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autofocus: true, "x-on:keydown.cmd.enter" => "$event.target.form.requestSubmit();" %>
    </div>

    <div class="grid justify-items-end">
      <%= form.button type: :submit, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" do %>
        <i class="fas fa-paper-plane"></i>
        <span class="pl-2">Send</span>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag message do %>
  <div id="<%= dom_id(message) %>_messages">
    <% if message.user? %>
      <div class="col-md-6">
        <p class="text-left"> <%= message.content %></p>
      </div>
    <% else %>
      <div class="col-md-6">
        <p class="text-right"> <%= message.content %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages", @message %>

<%= turbo_stream.replace "#{dom_id(@message.chat)}_message_form" do %>
  <%= render "form", chat: @message.chat %>
<% end %>

app/views/messages/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@message.chat)}_messages" %>